#!/usr/bin/python3

# Copyright (c) 2022 Firebuild Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Creates a CSV file describing the commits of the repository, which is
# used for the annotations (thin vertical lines) in Grafana.
#
# Written in python to provide consistent escaping of the comma and
# quotation mark characters with the rest of our tools.

import csv
import sys
import os

if len(sys.argv) != 2:
  print("Usage: generate_commits_csv firebuild_dir")
  sys.exit(1)

fbdir = sys.argv[1]

input = os.popen("git -C " + fbdir +  " log --format='format:%H %ct %s' HEAD")
with open("commits.csv", "w") as csvfile:
  writer = csv.writer(csvfile, lineterminator='\n')
  for row in input:
    hash, date, summary = row.strip().split(" ", 2)
    writer.writerow([hash[:12], date, summary])
