#!/usr/bin/python3

# Copyright (c) 2022 Firebuild Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Uploads the contents of some CSV files to MySQL.
# Drops the tables, destroying any previous contents, and re-creates them.
#
# See ../CSV_SCHEMA.txt for the explanation of the fields.

import csv
import mysql.connector  # apt-get install python3-mysql.connector

mysql_host = 'localhost'
mysql_user = 'fb'
mysql_pass = 'fb'
mysql_db   = 'fb'

conn = mysql.connector.connect(host=mysql_host, user=mysql_user, password=mysql_pass, database=mysql_db)
cursor = conn.cursor()

cursor.execute('DROP TABLE IF EXISTS buildtimes')
cursor.execute('CREATE TABLE buildtimes ('
                   'build_start_timestamp INT,'
                   'build_end_timestamp INT,'
                   'firebuild_version VARCHAR(40),'
                   'commit_timestamp INT,'
                   'project VARCHAR(50),'
                   'build_command VARCHAR(200),'
                   'exit_status SMALLINT,'
                   'real0 FLOAT,'
                   'user0 FLOAT,'
                   'sys0 FLOAT,'
                   'real1 FLOAT,'
                   'user1 FLOAT,'
                   'sys1 FLOAT,'
                   'real2 FLOAT,'
                   'user2 FLOAT,'
                   'sys2 FLOAT,'
                   'cachesize1 INT,'
                   'cachesize2 INT,'
                   'jobs INT)')

with open("buildtimes.csv") as csvfile:
  reader = csv.reader(csvfile)
  for (build_start_timestamp, build_end_timestamp,
       firebuild_version, commit_timestamp,
       project, build_command, exit_status,
       real0, user0, sys0,
       real1, user1, sys1,
       real2, user2, sys2,
       cachesize1, cachesize2, jobs) in reader:
    cursor.execute('INSERT INTO buildtimes VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)',
                   [int(build_start_timestamp), int(build_end_timestamp),
                    firebuild_version, int(commit_timestamp),
                    project, build_command, int(exit_status),
                    float(real0), float(user0), float(sys0),
                    float(real1), float(user1), float(sys1),
                    float(real2), float(user2), float(sys2),
                    int(cachesize1), int(cachesize2), int(jobs)])

cursor.execute('DROP TABLE IF EXISTS commits')
cursor.execute('CREATE TABLE commits ('
                   'firebuild_version VARCHAR(40),'
                   'timestamp INT,'
                   'subject VARCHAR(200) )')

with open("commits.csv") as csvfile:
  reader = csv.reader(csvfile)
  for firebuild_version, timestamp, subject in reader:
    cursor.execute('INSERT INTO commits VALUES(%s, %s, %s)',
                   [firebuild_version, int(timestamp), subject])

conn.commit()
cursor.close()
