#!/bin/sh -e

# Copyright (c) 2020 Interri Kft.
# This file is an unpublished work. All rights reserved.

# Create an image that already contains some of the essential stuff,
# including build-essential and whatever is needed to build firebuild.
#
# The lxc profile "firebuild-perftest" has to already exist.
#
# See README_SETUP.txt for further details.

BASE_IMG="${1:-ubuntu:focal}"

echo " · Launching lxc instance"
lxc launch -p firebuild-perftest "$BASE_IMG" firebuild-perftest-image-template

echo " · Waiting for cloud-init"
lxc exec firebuild-perftest-image-template -- cloud-init status --wait

echo " · Adding deb-src entries to sources.list"
lxc exec firebuild-perftest-image-template -- sh -c 'sed "s/^deb /deb-src /" < /etc/apt/sources.list > /etc/apt/sources.list.d/deb-src.list'

if lxc exec firebuild-perftest-image-template -- sh -c 'dpkg -l needrestart 2> /dev/null | grep -q "^i"'; then
    echo " · Removing needrestart"
    lxc exec firebuild-perftest-image-template -- eatmydata apt-get -y purge needrestart
fi

case $BASE_IMG in
    "ubuntu:focal")
        PPAS="ppa:rbalint/fmtlib ppa:rbalint/xxhash"
        ;;
    "ubuntu:impish")
        PPAS="ppa:rbalint/xxhash"
        ;;
    *)
        PPAS=""
esac

if [ -n "$PPAS" ]; then
    echo " . Adding PPAs for backported and fixed packages"
    for ppa in $PPAS; do
        lxc exec firebuild-perftest-image-template -- add-apt-repository -y -n $ppa
    done
fi

lxc exec firebuild-perftest-image-template -- apt-get update -qq
lxc exec firebuild-perftest-image-template -- apt-get upgrade -y

echo " · Disabling man-db creation"
lxc exec firebuild-perftest-image-template -- sh -c 'echo man-db man-db/auto-update boolean false | debconf-set-selections'

echo " · Removing packages with background jobs likely interfering with tests"
lxc exec firebuild-perftest-image-template -- eatmydata apt-get -y purge rsyslog unattended-upgrades

# This fails LP: #1878674
lxc exec firebuild-perftest-image-template -- eatmydata apt-get -y purge snapd || true

echo " · Disabling APT updates"
lxc exec firebuild-perftest-image-template -- sed -i s/1/0/ /etc/apt/apt.conf.d/10periodic

echo " · Purging unneeded packages"
lxc exec firebuild-perftest-image-template -- eatmydata apt-get -y autoremove

echo " · Stopping lxc instance"
lxc stop firebuild-perftest-image-template

if lxc image list | grep -qw firebuild-perftest-image-template; then
  echo " · Removing previous lxc image"
  lxc image delete firebuild-perftest-image-template
fi

echo " · Creating lxc image"
lxc publish --compression none firebuild-perftest-image-template --alias firebuild-perftest-image-template

echo " · Deleting lxc instance"
lxc delete firebuild-perftest-image-template

echo " · Done"
