#!/bin/sh -e

# Copyright (c) 2020 Interri Kft.
# This file is an unpublished work. All rights reserved.

# Create an image that already contains some of the essential stuff,
# including build-essential and whatever is needed to build firebuild.
#
# The lxc profile "firebuild-perftest" has to already exist.
#
# See README_SETUP.txt for further details.

echo " · Launching lxc instance"
lxc launch -p firebuild-perftest ubuntu:focal firebuild-perftest-image-template

echo " · Waiting for cloud-init"
lxc exec firebuild-perftest-image-template -- cloud-init status --wait

echo " · Adding deb-src entries to sources.list"
lxc exec firebuild-perftest-image-template -- sh -c 'sed "s/^deb /deb-src /" < /etc/apt/sources.list > /etc/apt/sources.list.d/deb-src.list'

echo " · Disabling man-db creation"
lxc exec firebuild-perftest-image-template -- sh -c 'echo man-db man-db/auto-update boolean false | debconf-set-selections'

# Background jobs could easily mess up the timing measurements.
# Double defense: disable in the config, and then remove the package (leaving the config files behind, just in case something reinstalls it).
echo " · Disabling unattended upgrades"
lxc exec firebuild-perftest-image-template -- sed -i s/1/0/ /etc/apt/apt.conf.d/10periodic /etc/apt/apt.conf.d/20auto-upgrades
lxc exec firebuild-perftest-image-template -- eatmydata apt-get -y remove unattended-upgrades

echo " · Installing essential packages"
lxc exec firebuild-perftest-image-template -- eatmydata apt-get update
lxc exec firebuild-perftest-image-template -- eatmydata apt-get -y install git build-essential cmake libconfig++-dev libevent-dev libflatbuffers-dev flatbuffers-compiler libxxhash-dev libjemalloc-dev python3-jinja2

echo " · Purging unneeded packages"
lxc exec firebuild-perftest-image-template -- eatmydata apt-get -y autoremove

echo " · Stopping lxc instance"
lxc stop firebuild-perftest-image-template

if lxc image list | grep -qw firebuild-perftest-image-template; then
  echo " · Removing previous lxc image"
  lxc image delete firebuild-perftest-image-template
fi

echo " · Creating lxc image"
lxc publish firebuild-perftest-image-template --alias firebuild-perftest-image-template

echo " · Deleting lxc instance"
lxc delete firebuild-perftest-image-template

echo " · Done"
