name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  full-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: |
        env -C perftest ./setup.sh
        sudo apt-get -y install eatmydata
        sudo eatmydata apt-get -y install r-base-core
    - name: test-firebuild
      run: |
        git clone https://github.com/firebuild/firebuild
        # use sudo to get lxd group membership
        sudo -u $USER env -C perftest ./outer -f ../firebuild json4s
        env -C firebuild git reset --hard HEAD~1
        sudo -u $USER env -C perftest ./outer -f ../firebuild json4s
    - name: check-results
      run: |
        cat ~/buildtimes.csv
        perftest/compare_builds.R ~/buildtimes.csv $(cut -d, -f3 ~/buildtimes.csv | tac)
    - name: option combinations
      run: |
        sudo -u $USER env -C perftest ./outer -d -j3 --keep-log --stop-on-first-failure -r --extra-version-string "options-test" --extra-fb-opts='-d time' --extra-fb-opts2='-g -s' --compressed-cache-size --timestamp-params="-i %.S" --enable-tests --separate-deb-prep -f ../firebuild json4s --tests-conf=tests.conf
    - name: check sanitization
      run: |
        # run sanitization on last Ubuntu version where GCC's ASan was not affected by
        # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110027
        sudo -u $USER env -C perftest ./create_template_image ubuntu:mantic
        sudo -u $USER env -C perftest ./outer -j3 --sanitize -r --extra-version-string "sanitized-test" --extra-fb-opts='-d time' -f ../firebuild json4s
